### ISSUE TITLE
Any reason to block on the version of dateutil

### ISSUE THREAD

**Issue by pypingou** [eventable/vobject#10]
In the setup.py at : https://github.com/eventable/vobject/blob/master/setup.py#L49
we impose a specific version of datetutil, does that mean that vobject doesn't work with 2.4.1 or 2.4.2?

It seems to say otherwise above: https://github.com/eventable/vobject/blob/master/setup.py#L14

So shouldn't we say ``>= 2.4.0`` ?

**Comment by sylvainvh** [comment]
Hi, 

I've the same error.
Thank for the pull request. I hope that Pull Request will be accepted.

**Comment by skarim** [comment]
dateutil 2.4.1 and 2.4.2 have issues with Python3: https://github.com/dateutil/dateutil/issues/145

It looks like the dateutil team is planning on fixing this in [2.5.0](https://github.com/dateutil/dateutil/issues/169), so I'm waiting until that release is out to update the requirements
