### ISSUE TITLE
vobject tries to base64-decode non-base64-encoded things

### ISSUE THREAD

**Issue by Hawk777** [eventable/vobject#100]
In vcard.py on line 139, you check whether the encoding variable is set and, if so, try to Base64-decode the value. Even if it’s set to, say, 8BIT. You never actually check that it’s set to Base64. This then crashes on trying to parse pretty much any 8bit-encoded field. This happened on 0.9.5.

**Comment by wpercy** [comment]
Can you provide a vCard that throws this error? I just want to make sure we're not short-circuiting something we shouldn't before I merge.

**Comment by Hawk777** [comment]
That’s an interesting question, and some further research I did has now revealed a lot I didn’t know about vCard before. I have a collection of vCards from two different sources: some where from my Android phone, while others I wrote by hand. Having investigated further, it turns out that, of the ones created on my phone, none of them has an `ENCODING` parameter at all, and they all obey vCard spec version 3.0, which according to RFC2426 encodes all its fields in 8-bit by default, and defers to RFC2425 to define the `ENCODING` parameter, of which only `b` is defined (base64).

The ones I wrote by hand, on the other hand, I was writing to vCard 2.1, which says in section 2.1.5 that all field values are encoded in 7-bit by default, and the `ENCODING` parameter can be set to one of `BASE64`, `QUOTED-PRINTABLE`, or `8BIT` if you want to change that.

So I think my pull request is definitely outright wrong for vCard 3.0 and higher, in which `b` means Base64-encoded, and my code will not match that, since `b` doesn’t contain `base64`. Yet when dealing with a vCard 2.1 file, it might be appropriate? I mean, honestly, I should probably just turn all my contacts into vCard 3.0 instead, since it’s almost two decades old. But I’ll leave it at your discretion whether you prefer me to rework it into something useful for vCard 2.1 only, or just throw it away. Let me know what you prefer.

**Comment by wpercy** [comment]
Yeah, we default to vCard 3.0. I suppose if you wanted to create a PR with another vCard class - something like VCard2_1 or something like that. You can model it after the [VCalendar2_0](https://github.com/eventable/vobject/blob/9885d9f4a1754245d05b5bc9da2b595e555fa529/vobject/icalendar.py#L911) class and the [VCard3_0 class](https://github.com/eventable/vobject/blob/9885d9f4a1754245d05b5bc9da2b595e555fa529/vobject/vcard.py#L170).

**Comment by Hawk777** [comment]
Even if vObject isn’t meant to support vCard 2.1, you don’t always get a choice—sometimes you’re consuming a file produced by some other application. Would it make sense to check the version number and reject values less than 3?
