### ISSUE TITLE
test_recurrence fails

### ISSUE THREAD

**Issue by dvzrv** [eventable/vobject#113]
During packaging for Arch Linux, test_recurrence fails, after successful build (for python2/3). I have shipped the package before, so I'm wondering, why it breaks now:

```
======================================================================
ERROR: test_recurrence (tests.TestIcalendar)          
----------------------------------------------------------------------
Traceback (most recent call last):           
  File "/build/python-vobject/src/python-vobject-0.9.5/tests.py", line 754, in test_recurrence
    dates = list(cal.vevent.getrruleset())                       
  File "/build/python-vobject/src/python-vobject-0.9.5/vobject/icalendar.py", line 453, in getrruleset
    ignoretz=isinstance(dtstart, datetime.date))
  File "/usr/lib/python3.6/site-packages/dateutil/rrule.py", line 1664, in __call__
    return self._parse_rfc(s, **kwargs)                
  File "/usr/lib/python3.6/site-packages/dateutil/rrule.py", line 1547, in _parse_rfc
    tzinfos=tzinfos)                     
  File "/usr/lib/python3.6/site-packages/dateutil/rrule.py", line 1506, in _parse_rfc_rrule
    return rrule(dtstart=dtstart, cache=cache, **rrkwargs)
  File "/usr/lib/python3.6/site-packages/dateutil/rrule.py", line 461, in __init__
    'RRULE UNTIL values must be specified in UTC when DTSTART '
ValueError: RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware
                                   
----------------------------------------------------------------------
Ran 39 tests in 0.182s                        
```

I'm running the tests with `python setup.py test`. Is there anything I'm missing?

**Comment by wpercy** [comment]
We don't use the setup.py test command, just run `python tests.py`.

**Comment by dvzrv** [comment]
Could you please take your time to actually look into this, instead of closing this bug? The test is still failing.

I'm also not sure, what your dismissive comment is supposed to tell me, but that you probably don't know what's going on in your [setup.py](https://github.com/eventable/vobject/blob/master/setup.py#L60)?
It clearly states `test_suite="tests"`.
Therefore it doesn't matter, if I call `python setup.py test` or `python tests.py`, as it will lead to the same result.

Apart from that, I guess currently having dateutil in version 2.7.3 on Arch Linux causes this behavior (as mentioned in #115), so this is a valid bug.

**Comment by wpercy** [comment]
Yes, this is caused by us not currently supporting dateutil 2.6+. I'll test against the PR you referenced above when I get a chance and put out a new release.

**Comment by dvzrv** [comment]
Thanks! :+1:
