### ISSUE TITLE
Old (version: 2.1) vCard does not read or reads with errors!

### ISSUE THREAD

**Issue by YuraKursk** [eventable/vobject#118]
Why does not it read 2.1 versions correctly?
I'll have to write the code handler. Before downloading an object 'version:2.1'?

If I uploaded to the vCard object 'version: 3.0'. Unload object 'version: 2.1' not possible!

**Comment by YuraKursk** [comment]
#### Does anyone know how to load a 2.1 vCard into a module vobject?
   #### Only version 3.0 is downloaded to the module
   #### How to unload in this version 2.1?

**Comment by wpercy** [comment]
Hi! We currently don't support vCard 2.1, we default to 3.0. I have no current plans to write 2.1 support, but if you want to, feel free and I'd be happy to review it!

**Comment by YuraKursk** [comment]
Hey. Does it make sense to support version 3.0 without version 2.1?
New smartphones (Android) support only version 2.1
My old Androyd worked with version 3.0 and now information (for example, Birthday) is lost due to incompatibility.
