### ISSUE TITLE
vCard: REV is not DATE or DATETIME

### ISSUE THREAD

**Issue by Unrud** [eventable/vobject#120]
It's a timestamp: https://tools.ietf.org/html/rfc6350#section-6.7.4

E.g. the valid timestamp ``2018-01-01T00:00:00Z`` doesn't work and causes an exception.

The bug was introduced in https://github.com/eventable/vobject/commit/6462c67320e387ebf49f769bbcb2933d0583860f.

**Comment by Arvedui** [comment]
I just stumbled upon this while trying to write an e-mail after updating to 0.9.6. 
Are there any plans for fixing this?

**Comment by quite** [comment]
According to RFC6350 4.3.1. DATE, the "expanded" format of ISO.8601.2004 is forbidden. I don't have access to the ISO document, but the Internets have references to an "extended" format in which `-` separators are used. As for 4.3.2. TIME, the "expanded" format is not forbidden here. But perhaps it's dictated somewhere else that it's both date and time expanded, or none. Lot's of guessing...

Being hard on not using expanded format seems to be in accordance with RFC, but I think various current implementations produce expanded format. I got 20% such of hundreds of entries.

**Comment by benoliver999** [comment]
What @quite said.

I'm slowly but surely finding out that few apps actually stick to the standard. I don't think it's on this project to change, but just a heads up for when people start getting updates that break things...

**Comment by wpercy** [comment]
I'll leave this open for now to continue the discussion.

@Unrud 
> E.g. the valid timestamp `2018-01-01T00:00:00Z` doesn't work and causes an exception.

`2018-01-01T00:00:00Z` is an invalid timestamp according to the RFC, like @quite pointed out, so this isn't a _true_ bug, but it's definitely something I'd like to continue hearing opinions on. 

However, if someone were to open a PR that modified the `DateOrTimeBehavior`, or added a `TimestampBehavior` class, I'd be happy to have a look.

**Comment by benoliver999** [comment]
OK someone over at ez-vcard pointed out that vcard 3.0 (RFC 2426) does actually use the extended format.

**Comment by wpercy** [comment]
@here it looks like this is more a compatability issue between vCard 2.1 and 3.0, I'll work on a stopgap fix, but the real solution here is for someone to write a vCard 3.0 parser.

**Comment by wpercy** [comment]
okay because this had affected so many other implementations I've decided to revert the offending commit - thanks for the discussion folks, 0.9.6.1 is out now

**Comment by enkore** [comment]
Thanks for the fix. I think you might have forgotten a `git push --tags`, since no 0.9.6.1 tag exists yet (ab1d7fd8a)
