### ISSUE TITLE
AttributeError: 'str' object has no attribute 'family'

### ISSUE THREAD

**Issue by yanone** [eventable/vobject#128]
Hi,

I'm porting my code to Python 3 and writing test routines.  vobject currently chokes on the following code:

```python
name = 'Max Mustermann'
email = 'max@mustermann.de'
vcard = vobject.vCard()

try: assert vcard.n
except: vcard.add('n')
vcard.n.value = name

try: assert vcard.fn
except: vcard.add('fn')
vcard.fn.value = name

try: assert vcard.email
except: vcard.add('email')
vcard.email.value = email

serialized = vcard.serialize()
```

with the following traceback:

```
Traceback (most recent call last):
File "/home/juicie/wsgi/py/vobject/base.py", line 215, in transformFromNative
return self.behavior.transformFromNative(self)
File "/home/juicie/wsgi/py/vobject/vcard.py", line 310, in transformFromNative
obj.value = serializeFields(obj.value, NAME_ORDER)
File "/home/juicie/wsgi/py/vobject/vcard.py", line 277, in serializeFields
toList(getattr(obj, field))]
AttributeError: 'str' object has no attribute 'family'
```

It used to work with my old code. What am I doing wrong?
Thank you.

**Comment by wpercy** [comment]
When you say "it used to work with my old code", what do you mean? It worked in python 2? It worked with an older version of vobject?

**Comment by yanone** [comment]
Yes, it worked in Python 2 and *probably* an older version of `vobject`, though I can't find a version number in the `vobject` code right now. All is running on a normal web server without root access, so I just copy code over without `pip` or other code management.

That aside, shouldn't the simple code that I posted work? It's Python 3.4.3 and the latest `vobject` code.

**Comment by wpercy** [comment]
Okay, I think you should be using the `Name` constructor when creating your `N` attribute. Something like this:

```
name = 'Max Mustermann'
email = 'max@mustermann.de'
vcard = vobject.vCard()

try: assert vcard.n
except: vcard.add('n')
vcard.n.value = vobject.vcard.Name(family=name.split()[-1], given=name.split()[0])

try: assert vcard.fn
except: vcard.add('fn')
vcard.fn.value = name

try: assert vcard.email
except: vcard.add('email')
vcard.email.value = email

serialized = vcard.serialize()
print(serialized)
```

returns

```
BEGIN:VCARD
VERSION:3.0
EMAIL:max@mustermann.de
FN:Max Mustermann
N:Mustermann;Max;;;
END:VCARD
