### ISSUE TITLE
How to get PREF parameter?

### ISSUE THREAD

**Issue by NicoHood** [eventable/vobject#129]
I  got two phone entries:
```
TEL;TYPE=HOME:+49...
TEL;PREF;TYPE=CELL:+49...
```

If I print all parameters `PREF` is not shown:
```python
    with open(address_book_path) as vcf_file:
        v = list(vobject.readComponents(vcf_file))

    for k in v:
        k.prettyPrint()
        for phone_number in k.tel_list:
            print(phone_number.params)

{'TYPE': ['HOME']}
{'TYPE': ['CELL']}
```

I'd like to get the pref attribute, as I want to send out SMS to the preferred phone number. If multiple exist, the first one is picked. But the problem is that the data deserialization seems to lose this information/i dont know where to get it from.

**Comment by NicoHood** [comment]
`phone_number.singletonparams` Was the solution. Maybe more examples should be added to the Readme? Or a proper documentation...

**Comment by WolfgangFahl** [comment]
Why is this closed? I have same problem and do not understand how singletonparams might be used since there seems to be still no example.

**Comment by WolfgangFahl** [comment]
This is my workaround:
```
if primary==identifier:
                        # need to set PREF here - but how?
                        # https://github.com/eventable/vobject/issues/129
                        typeParam=[typeParam,"pref"]
```
