### ISSUE TITLE
Make vobject python3-compatible

### ISSUE THREAD

**Issue by prauscher** [eventable/vobject#20]
althrough vobject is distributed as python3-compatible, it contains lines like https://github.com/eventable/vobject/blob/master/vobject/vcard.py#L137 - str.decode("base64") etc is only supported in python2, so using vobject in a python3-environment especially fails when base64-encoded photos or such are parsed.

**Comment by Rondom** [comment]
@prauscher I think you should use the encoding given in the vcard-file for decoding the quoted-printable encoded fields instead of defaulting to UTF-8. It is available as a variable a few lines further up.

It would be really nice if you could add some test case reproducing the issue to make sure we handle encoded characters correctly on all Python versions

**Comment by prauscher** [comment]
@Rondom the encoding given in the line above is "b" for base64. I currently see no other encoding-variable than "utf-8"

A simple test case should be
```
BEGIN:VCARD
VERSION:3.0
N:Meister Ede
FN;ENCODING=b:TWVpc3RlciBFZGU=
END:VCARD
```
the parsed FN should equal to the parsed N - "Meister Ede". You can see that fun even increases when PHOTO is involved ;)

**Comment by srepmub** [comment]
running into similar problem, and above patch seems to fix it. example fragment:

LABEL;WORK;ENCODING=QUOTED-PRINTABLE:100 Waters Edge=0D=0ABaytown, LA 30314=0D=0AUnited States of America

I don't see where to get the encoding either.. it's not in my VCARD test file.

**Comment by srepmub** [comment]
oh, I guess it can be added to the VCARD as follows:

LABEL;HOME;ENCODING=QUOTED-PRINTABLE;CHARSET=UTF-8:42 Plantation St..

according to this:

https://www.imc.org/pdi/vcal-10.txt

it also mentions that the default encoding is ASCII.. so we take CHARSET or default to ASCII..?

**Comment by prauscher** [comment]
Mhh. I'm not sure if defaulting to ASCII is a good thing, as this will break as soon as any ä, ö. ü or related is contained (which would be against the standard probably, but I have seen several iCals without the CHARSET-option). As UTF-8 is ASCII extended, i'd leave UTF-8 as default.

**Comment by srepmub** [comment]
that sounds fine to me.. would you feel like adding some test cases to your patch..? I'd be happy to give that a try as well..
