### ISSUE TITLE
prints to standard out on invalid timezone

### ISSUE THREAD

**Issue by jelmer** [eventable/vobject#22]
vobject currently prints to standard out when it encounters an invalid timezone. It would be great if it could e.g. use a logger instead so the message could be silenced.

**Comment by lucc** [comment]
#35 is in master now. Does that fix it?

**Comment by jelmer** [comment]
On Fri, Aug 26, 2016 at 03:49:23PM -0700, Lucas Hoffmann wrote:
> #35 is in master now. Does that fix it?
Yep, thanks!
