### ISSUE TITLE
I get new lines within the url (maybe if they are too long)

### ISSUE THREAD

**Issue by mhaze4** [eventable/vobject#25]
Hi,

I use vobject to generate vCards for persons on a website.
Each person has its own detail page which is located for example on

`https://example.org/about-us/our-team/firstname-lastname`

but this example is a short one, I have one url with a length of 84 chars for a person where I experience this behaviour.

I have proved the generated strings again and again but the new line appears only in the output string of the serialize function. Even the value field of the url list item of the vobject does not have new lines.

The whole part after the new line is ignored and the url does not work

**Comment by untitaker** [comment]
I think that's intended behavior. Line wrapping is done for serialization, but deserializing should remove the wrapping again.

**Comment by wpercy** [comment]
This is indeed intended behavior. From [RFC 6350](https://tools.ietf.org/html/rfc6350#section-3.2):
> Content lines SHOULD be folded to a maximum width of 75 octets, excluding the line break.
