### ISSUE TITLE
Do you need help with maintenance?

### ISSUE THREAD

**Issue by untitaker** [eventable/vobject#52]
It appears that this library contains some super-critical bugs such as #51, though PRs take a long time to get merged. Do you need help with maintaining this library?

**Comment by skarim** [comment]
Apologies, we've been very busy! @wpercy will be leading maintenance of vobject and we are starting to get these critical issues fixed right now!

**Comment by wpercy** [comment]
👍

**Comment by jelmer** [comment]
Thanks for the updates! Any chance of a new release with the recent set of fixes?

**Comment by wpercy** [comment]
Yep, I'm hoping to be able to put out a new release late this week/early next week - trying to fix these pesky unicode bugs now.
