### ISSUE TITLE
Failing unit-tests

### ISSUE THREAD

**Issue by pypingou** [eventable/vobject#61]
When trying to update the package on Fedora, I ran into this error in the test suite:

~~~~
======================================================================
FAIL: test_general_behavior (tests.TestBehaviors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/vobject-0.9.4.1/tests.py", line 225, in test_general_behavior
    'VTIMEZONE', 'VTODO']
AssertionError: Lists differ: ['', [234 chars]Y', 'HCALENDAR', 'LABEL', 'LAST-MODIFIED', 'LO[291 chars]ODO'] != ['', [234 chars]Y', 'LABEL', 'LAST-MODIFIED', 'LOCATION', 'MET[278 chars]ODO']
First differing element 23:
'HCALENDAR'
'LABEL'
First list contains 1 additional elements.
First extra element 52:
'VTODO'
Diff is 740 characters long. Set self.maxDiff to None to see it.
~~~~

The full log is available there: https://kojipkgs.fedoraproject.org//work/tasks/7622/17427622/build.log

Would you have an idea of what is going on?

Thanks :)

**Comment by lucc** [comment]
Did you run `python setup.py test` or `python test.py`? The latter is taken from the travis file, the former was what I ran intuitifly. For me the former gives a failure similar to yours and the latter succeeds (with 37 tests).

**Comment by pypingou** [comment]
It runs ``python setup.py test`` pity the logs have been cleaned I can kick off another build if desired

**Comment by lucc** [comment]
I think you should run python test.py like in the travis file.

**Comment by pypingou** [comment]
Shouldn't the setup.py file be adjusted then?

**Comment by lucc** [comment]
It's python so "there should be (only) one obvious way to do it", so maybe yes.

**Comment by wpercy** [comment]
Can you pull down the [update-setup branch](https://github.com/eventable/vobject/tree/update-setup) and let me know if that builds correctly? When I run `python setup.py test` on OSX, I don't even find any tests.

**Comment by pypingou** [comment]
https://koji.fedoraproject.org/koji/taskinfo?taskID=17970033 Alright the tests are now running and passing :)
