### ISSUE TITLE
Parsing Error in "ATTENDEE" line

### ISSUE THREAD

**Issue by htgoebel** [eventable/vobject#72]
Hi, the following link fails to parse:

vobject.base.ParseError: At line 12: Failed to parse line: 
`ATTENDEE;RSVP=TRUE;CN=John Doe;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPANT;SCHEDULE-STATUS="3.7;Invalid Calendar User";INVALID CALENDAR USER":mailto:john.doe@example.com`

**Comment by wpercy** [comment]
It looks like you're missing a double-quote somewhere.

**Comment by htgoebel** [comment]
Maybe. But this is a read-life example.

**Comment by wpercy** [comment]
What do you mean it's a "read-life example"? The property is incorrectly formatted, it correctly throws a ParseError.

**Comment by htgoebel** [comment]
Well, IMHO the parser needs to be resilient against this kind of errors. The event was generated by some software – wich might be buggy, but insisting on this does not help the user having this event.
