### ISSUE TITLE
Parsing error: X-ALT-DESC with HTML

### ISSUE THREAD

**Issue by htgoebel** [eventable/vobject#73]
Parsing the enclosed event [error1.txt](https://github.com/eventable/vobject/files/1022348/error1.txt) fails with vobject.base.ParseError: At line 248: `Failed to parse line: <HTML>`. Relevant part is:
```
SEQUENCE:0
TRANSP:OPAQUE
X-ALT-DESC:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
<HEAD>
…
```
Yes, the continuation lines are *not* indented.

**Comment by wpercy** [comment]
Your format is wrong. According to the [Microsoft spec](https://msdn.microsoft.com/en-us/library/ee237480(v=exchg.80).aspx) for X-ALT-DESC, the format needs to be "Text", defined in [RFC2445](https://www.ietf.org/rfc/rfc2445.txt) section 4.3.11. This means that you need to fold the HTML lines like you would any other line of text longer than the 75 octets specified in 2445.

**Comment by htgoebel** [comment]
This is an real-live example, not something I generated.

**Comment by wpercy** [comment]
That's fine, but this is a correctly thrown ParseError. How is vObject supposed to know that the next line is part of the previous property if it's not properly folded? What client generated that vCalendar?
