### ISSUE TITLE
How to access multi-type entries for e.g. TEL?

### ISSUE THREAD

**Issue by htgoebel** [eventable/vobject#78]
I could not find an example how to access and how to set multi-type entries like
```
TEL;TYPE=work:+49-…
TEL;TYPE=cell,work:+49-…
TEL;TYPE=fax,work:+49-…
```
Can you please add an example? Thanks.

**Comment by hyshka** [comment]
I'm trying to figure out how to do the same thing, any progress @htgoebel ?

**Comment by htgoebel** [comment]
I was able to access the values like this:

    for line in addr.contents.get('email', []):
        line.params.setdefault('TYPE', []).append('pref')

**Comment by hyshka** [comment]
Thanks @htgoebel that helped me access them.
