### ISSUE TITLE
How to create multi-value entries for e.g. TEL?

### ISSUE THREAD

**Issue by htgoebel** [eventable/vobject#80]
Thanks for improving the documentation about multi-value entries (see #78, #79). When rethinking this, I found a few more places for improvement:

#### 1. How to *create* multi-value entries

The [example](http://eventable.github.io/vobject/#creating-vcard-objects) from the documentation only shows a simple entry. This is an example for adding a second entry:
```
>>> import vobject
>>> j = vobject.vCard()
>>> e1 = j.add('email')
>>> j.email.value = 'jeffrey@osafoundation.org'  # intentionally using a different way here
>>> e2 = j.add('email')
>>> e2.value = "john@example.com"
>>> e1
<EMAIL{}jeffrey@osafoundation.org>
>>> e2
<EMAIL{}hartmut@goe-con.de>
>>> j.email
<EMAIL{}jeffrey@osafoundation.org>
```

#### 2. How to determine if an entry is multi-valued?

According to this test, it seems that `email` entries (and presumable `tel` etc.) are always lists:
```
>>> k = vobject.vCard()
>>> k.add('email')
<EMAIL{}>
>>> k.contents['email'].__class__
<class 'list'>
```

Please documents this and also which entries are lists.

**Comment by wpercy** [comment]
Feel free to make a Pull Request with any changes you think would be helpful.
