### ISSUE TITLE
PHOTO Property is stripped of base64 data

### ISSUE THREAD

**Issue by potuz** [eventable/vobject#87]
I have also posted this in https://github.com/Kozea/Radicale/issues/648

Using vdirsyncer to send the following vcard to radicale 2.0.0 and vobject 0.9.4.1

```
$cat ~/.contacts/personal/dgv1qx53rhbj74q91nm0u5wansopz0xgrfex.vcf
BEGIN:VCARD
VERSION:4.0
UID:dgv1qx53rhbj74q91nm0u5wansopz0xgrfex
EMAIL;TYPE=home:cansado@dormire.com
FN:Dormire Cansado
N:Cansado;Dormire;;;
REV:20170626T215407Z
PHOTO:data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/4XYsRXhpZgAATU0AKgAAAAgACQEPAAIAAAAJAAAAegEQAAIAAAAHAAAAhA......
.....98UqVKh+wnu//9k=
END:VCARD
```

I get this on the server:
```
#cat personal/dgv1qx53rhbj74q91nm0u5wansopz0xgrfex.vcf
BEGIN:VCARD
VERSION:4.0
UID:dgv1qx53rhbj74q91nm0u5wansopz0xgrfex
EMAIL;TYPE=home:cansado@dormire.com
FN:Dormire Cansado
N:Cansado;Dormire;;;
PHOTO:data:image/jpeg\;base64
REV:20170626T215407Z
END:VCARD
```
And of course the photo is not seen on any client synchronizing this. 

This is trying to get a base64 encoded picture on a version 4.0 vcard. <s>When I try to use a version 3.0 I hit the error in #59 and #39</s>

**Comment by potuz** [comment]
Argh, I just read in vobject/vcard.py 
```
"""Definitions and behavior for vCard 3.0"""
```
I guess I'll have to switch my default to version 3.0

**Comment by wpercy** [comment]
Yep, and when you switch over to 3.0, make sure you change your encoding parameter to just `b` not `BASE64`
