### ISSUE TITLE
vcard objects don't format datetime objects for serialisation

### ISSUE THREAD

**Issue by goetzk** [eventable/vobject#93]
Hi,
When trying to serialise() a card with a date time for BDAY I'm seeing a validation error. prettyPrint works quite fine.
I had a look in git but only see reference to BDAY in the test corpus.
https://github.com/eventable/vobject/blob/master/vobject/vcard.py
http://eventable.github.io/vobject/ mentions that using date time objects works, does that refer specifically to the calendar side?

Example output from pretty print (yes, real information replaced):
```
 VCARD
    BDAY: 1999-01-25 00:00:00
    NOTE: Imported from N900 via awful mangling script
    REV: 2017-08-26 11:15:36.637242
    FN: Karl Goetz
    N:  Karl Goetz   
```

Error from serialise
```
(n900-migrations) Karls-Air:.calendar kgoetz$ python migrate_calendar.py 
Traceback (most recent call last):
  File "migrate_calendar.py", line 196, in <module>
    export_to_vcard(current_data)
  File "migrate_calendar.py", line 184, in export_to_vcard
    print card.serialize()
  File "/Users/kgoetz/virtualenvs/n900-migrations/lib/python2.7/site-packages/vobject/base.py", line 254, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/Users/kgoetz/virtualenvs/n900-migrations/lib/python2.7/site-packages/vobject/behavior.py", line 166, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
  File "/Users/kgoetz/virtualenvs/n900-migrations/lib/python2.7/site-packages/vobject/base.py", line 1007, in defaultSerialize
    child.serialize(outbuf, lineLength, validate=False)
  File "/Users/kgoetz/virtualenvs/n900-migrations/lib/python2.7/site-packages/vobject/base.py", line 254, in serialize
    return behavior.serialize(self, buf, lineLength, validate)
  File "/Users/kgoetz/virtualenvs/n900-migrations/lib/python2.7/site-packages/vobject/behavior.py", line 166, in serialize
    out = base.defaultSerialize(transformed, buf, lineLength)
  File "/Users/kgoetz/virtualenvs/n900-migrations/lib/python2.7/site-packages/vobject/base.py", line 1015, in defaultSerialize
    obj.behavior.encode(obj)
  File "/Users/kgoetz/virtualenvs/n900-migrations/lib/python2.7/site-packages/vobject/vcard.py", line 161, in encode
    line.value = backslashEscape(line.value)
  File "/Users/kgoetz/virtualenvs/n900-migrations/lib/python2.7/site-packages/vobject/base.py", line 1216, in backslashEscape
    s = s.replace("\\", "\\\\").replace(";", "\;").replace(",", "\,")
TypeError: an integer is required
```

Update:
I realised I hadn't included any code.

```
def export_to_vcard(data):
  """Take data from sqlite and convert it to a vcard file"""
  # data is a list.
  card = vobject.vCard()
  card.add('fn')
  card.fn.value = data[6] # string
  card.add('bday')
  card.bday.value = data[4] # date time object
  card.add('note')
  card.note.value = 'Imported from N900 via awful mangling script'
  card.add('rev')
  card.rev.value = datetime.datetime.now()
  print card.serialize()
```

**Comment by goetzk** [comment]
This appears to be an issue with date time object handling, commenting out bday but leaving card.rev.value as a datettime generates the same error. commenting both out the card serialises.

**Comment by wpercy** [comment]
@goetzk my guess is that this is intentionally ambiguous to allow for matching the spec in the exact way intended by the user. [RFC 3650 - vCard Format Specification (section 6.2.5)](https://tools.ietf.org/html/rfc6350#section-6.2.5) says that the value can be either a "single date-and-time-value" or a "single text value". Here's the [date-and-or-time definition](https://tools.ietf.org/html/rfc6350#section-4.3.4) in the same RFC.

**Comment by wpercy** [comment]
REV, on the other hand, is a timestamp value, so that should definitely be fixed.

**Comment by goetzk** [comment]
@wpercy thanks for the background. Given that I can agree the library shouldn't necessarily convert bday for me but I wonder what the correct resolution becomes. Options I can see are:
* A few lines of documentation noting that date-and-or-time fields need to be manually formatted
* Library notices the value is a date time and raises an error of some sort indicating the data needs formatting

If you'd like me to take a stab at writing the documentation I'm happy to have a  go later in the week.

thanks,
kk

**Comment by wpercy** [comment]
You're absolutely right, we should never assume such close familiarity with the spec. I'll definitely add some lines to the docs and take a stab at raising a more helpful exception if it's not too difficult. Thanks for the report!

**Comment by goetzk** [comment]
On 29/8/17 10:53, Will Percival wrote:
> You're absolutely right, we should never assume such close familiarity
> with the spec. I'll definitely add some lines to the docs and take a
> stab at raising a more helpful exception if it's not too difficult.
> Thanks for the report!

Thanks for taking it on!
kk
